# Generated by Django 3.2.5 on 2022-05-28 21:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('albums', '0004_cpu_ram'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='CPU',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='albums.cpu'),
        ),
    ]
