# Generated by Django 3.2.5 on 2022-05-28 21:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('albums', '0005_album_cpu'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RAM',
        ),
        migrations.RemoveField(
            model_name='album',
            name='CPU',
        ),
        migrations.AddField(
            model_name='cpu',
            name='Album',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='CPUs', to='albums.album'),
        ),
    ]
