# Generated by Django 3.2.5 on 2022-05-29 12:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('albums', '0006_auto_20220528_2334'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cpu',
            name='Album',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='CPU', to='albums.album'),
        ),
    ]
