# Generated by Django 3.2.5 on 2022-05-29 13:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('albums', '0007_alter_cpu_album'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cpu',
            name='Album',
        ),
        migrations.AddField(
            model_name='cpu',
            name='album',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='album', to='albums.album'),
        ),
    ]
