# Generated by Django 3.2.5 on 2022-05-29 15:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('albums', '0008_auto_20220529_1521'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cpu',
            name='album',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='CPU', to='albums.album'),
        ),
    ]
