# Generated by Django 3.2.5 on 2022-06-12 20:21

import albums.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('albums', '0010_delete_cpu'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=albums.models.upload_path),
        ),
    ]
