# Generated by Django 3.2.5 on 2022-06-13 16:44

import albums.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('albums', '0011_album_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImagesAlbum',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imageAlbum', models.ImageField(blank=True, null=True, upload_to=albums.models.upload_path_2)),
            ],
        ),
        migrations.AddField(
            model_name='album',
            name='imagesAlbum',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='albums.imagesalbum'),
        ),
    ]
