# Generated by Django 3.2.5 on 2022-06-13 18:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('albums', '0012_auto_20220613_1844'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='album',
            name='imagesAlbum',
        ),
        migrations.DeleteModel(
            name='ImagesAlbum',
        ),
    ]
