# Generated by Django 3.2.5 on 2022-06-29 21:32

import albums.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('albums', '0014_auto_20220616_1936'),
    ]

    operations = [
        migrations.RenameField(
            model_name='albumimage',
            old_name='image',
            new_name='image_url',
        ),
        migrations.AlterField(
            model_name='album',
            name='cover_photo',
            field=models.ImageField(blank=True, default='fondGris.jpg', null=True, upload_to=albums.models.upload_path),
        ),
        migrations.AlterField(
            model_name='albumimage',
            name='album',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='albums.album'),
        ),
    ]
